# Generated by Django 6.1 on 2026-08-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='apellidos')),
                ('phone', models.CharField(help_text='E.164, e.g. +573167687288', max_length=20, verbose_name='teléfono')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, drives the flag', max_length=2, verbose_name='país')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='mail')),
                ('channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=20, verbose_name='canal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
