# Generated by Django 6.1 on 2026-08-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre del grupo')),
                ('created_by', models.CharField(blank=True, max_length=80, verbose_name='creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('clients', models.ManyToManyField(blank=True, related_name='client_lists', to='core.client', verbose_name='clientes')),
            ],
            options={
                'verbose_name': 'lista de clientes',
                'verbose_name_plural': 'listas de clientes',
                'ordering': ['name'],
            },
        ),
    ]
