# Generated by Django 6.1 on 2026-08-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('template_type', models.CharField(blank=True, max_length=40, verbose_name='tipo')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='categoría')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('team', models.CharField(blank=True, max_length=80, verbose_name='equipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plantilla de WhatsApp',
                'verbose_name_plural': 'plantillas de WhatsApp',
                'ordering': ['name'],
            },
        ),
    ]
