# Generated by Django 6.1 on 2026-08-28 17:59
# (hand-edited: a dedupe step runs before AddConstraint -- see below)

from django.db import migrations, models


def dedupe_names(apps, schema_editor):
    """Uniqueness on (name, language) was legal to violate before this
    migration, so rename any duplicates -- "welcome", "welcome (2)"... --
    before the constraint lands. Every row shares language='es' here (the
    field was added moments ago with that default)."""
    MessageTemplate = apps.get_model('core', 'MessageTemplate')
    seen = {}
    for template in MessageTemplate.objects.order_by('name', 'id'):
        count = seen.get(template.name, 0) + 1
        seen[template.name] = count
        if count > 1:
            template.name = f'{template.name} ({count})'
            template.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='body_sample_values',
            field=models.JSONField(blank=True, default=list, verbose_name='valores de ejemplo'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=list, verbose_name='botones'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=80, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='footer',
            field=models.CharField(blank=True, max_length=60, verbose_name='pie de página'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='header_media',
            field=models.FileField(blank=True, upload_to='plantillas/', verbose_name='archivo de cabecera'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='header_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='texto de cabecera'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='header_type',
            field=models.CharField(choices=[('none', 'Ninguno'), ('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], default='none', max_length=10, verbose_name='cabecera'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(default='es', max_length=10, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(blank=True, verbose_name='cuerpo'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Autenticación')], default='marketing', max_length=20, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='sub_type',
            field=models.CharField(choices=[('custom', 'Mensaje personalizado'), ('limited_time_offer', 'Oferta de tiempo limitado'), ('carousel', 'Carrusel'), ('auth_code', 'Código de autenticación')], default='custom', max_length=30, verbose_name='tipo'),
        ),
        migrations.RunPython(dedupe_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='unique_template_name_per_language'),
        ),
    ]
