# Generated by Django 6.1 on 2026-08-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_map_legacy_template_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='todo el día')),
                ('event_type', models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], default='reunion', max_length=20, verbose_name='tipo')),
                ('reminder_minutes_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='recordatorio (minutos antes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='asignado a')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='core.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'evento de calendario',
                'verbose_name_plural': 'eventos de calendario',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['start', 'assigned_to'], name='calendar_start_advisor_idx')],
            },
        ),
    ]
