# Generated by Django 6.1 on 2026-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_status',
            field=models.CharField(blank=True, max_length=24, verbose_name='estado en Meta'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sincronizado con Meta'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_template_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='id en Meta'),
        ),
    ]
