# Generated by Django 6.1 on 2026-09-04 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='texto')),
                ('image', models.FileField(blank=True, upload_to='respuestas/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_replies_created', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'respuesta rápida',
                'verbose_name_plural': 'respuestas rápidas',
                'ordering': ['title'],
            },
        ),
    ]
