# Generated by Django 6.1 on 2026-09-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quickreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='provider_template_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='id en el proveedor'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='status_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estado sincronizado'),
        ),
    ]
