# Generated by Django 6.1 on 2026-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messagetemplate_provider_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_enabled', models.BooleanField(default=False, verbose_name='bienvenida activa')),
                ('welcome_body', models.TextField(blank=True, verbose_name='mensaje de bienvenida')),
                ('assign_enabled', models.BooleanField(default=False, verbose_name='asignación automática activa')),
                ('assign_strategy', models.CharField(choices=[('round_robin', 'Por turnos entre los agentes activos')], default='round_robin', max_length=20, verbose_name='estrategia')),
                ('assign_cursor', models.PositiveIntegerField(default=0, verbose_name='turno actual')),
                ('widget_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono del widget')),
                ('widget_greeting', models.CharField(blank=True, default='Hola, quiero más información.', max_length=140, verbose_name='saludo del widget')),
                ('widget_label', models.CharField(blank=True, default='Escríbenos', max_length=40, verbose_name='texto del botón')),
                ('widget_position', models.CharField(choices=[('right', 'Abajo a la derecha'), ('left', 'Abajo a la izquierda')], default='right', max_length=10, verbose_name='posición')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de mensajería',
                'verbose_name_plural': 'configuración de mensajería',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bienvenida enviada'),
        ),
    ]
