# Generated by Django 6.1 on 2026-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_messaging_automations'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='token')),
                ('content', models.BinaryField(verbose_name='contenido')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='tipo')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamaño')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archivo almacenado',
                'verbose_name_plural': 'archivos almacenados',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
