"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# True under `manage.py test` (and pytest). core.middleware.LoginRequiredMiddleware
# reads this so the test client -- which never logs in -- isn't locked out.
TESTING = 'test' in sys.argv

# Load BASE_DIR/.env into os.environ before anything below reads it, so a
# plain `python manage.py ...` picks up local credentials with no `export`
# step. Real environment variables take precedence -- load_dotenv does not
# override what is already set -- so Vercel's project env vars win in
# production, where no .env file is deployed in the first place.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY in the environment for any real deployment (e.g. Vercel
# project env vars); this fallback is only for local development.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-r9ns&rk(gu0yvwjj&%#pepbj_oh_26h@pwex8#ch^x90+is@($',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Vercel sets VERCEL_URL to the deployment's hostname (no scheme) on every
# build, including preview deployments -- trust it automatically so the app
# works without listing every preview URL by hand. VERCEL_URL is per-deployment
# (e.g. mvp-crm-xxxxx.vercel.app) and does NOT cover the stable production
# alias, so VERCEL_PROJECT_PRODUCTION_URL is trusted too.
VERCEL_URL = os.environ.get('VERCEL_URL')
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)

VERCEL_PROJECT_PRODUCTION_URL = os.environ.get('VERCEL_PROJECT_PRODUCTION_URL')
if VERCEL_PROJECT_PRODUCTION_URL:
    ALLOWED_HOSTS.append(VERCEL_PROJECT_PRODUCTION_URL)

# Vercel also assigns this project two more stable aliases beyond
# VERCEL_PROJECT_PRODUCTION_URL (project-name-team-slug, and the git branch
# alias for main) -- hardcode them so they keep working without a dashboard
# env var edit. Only on Vercel (it sets VERCEL=1): locally these entries
# would make ALLOWED_HOSTS non-empty and disable Django's DEBUG-mode
# localhost fallback, locking the dev server out of its own machine.
if os.environ.get('VERCEL'):
    ALLOWED_HOSTS += [
        'mvp-crm-unaneaprogramadora.vercel.app',
        'mvp-crm-git-main-unaneaprogramadora.vercel.app',
    ]

CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

# Vercel terminates TLS in front of the app and forwards over HTTP; without
# this, request.is_secure() is always False behind the proxy, which breaks
# CSRF checks and any secure-cookie/redirect behavior.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Who can log in, and who a conversation can be assigned to -- the same list
# either way (see core/agents.py for the format and the reasoning). Comma-
# separated `username:password:Nombre` entries, e.g.
#   APP_AGENTS=Admin:sup3rsecret:Admin,Samuel:1234:Samuel
# Blank means the gate can never be satisfied (see core.middleware), rather
# than an empty/empty login working.
APP_AGENTS = os.environ.get('APP_AGENTS', '')

# The pre-agents single pair, kept as a fallback so an environment that only
# sets these two still gets in -- core.agents treats it as a one-agent list.
APP_LOGIN_USERNAME = os.environ.get('APP_LOGIN_USERNAME', '')
APP_LOGIN_PASSWORD = os.environ.get('APP_LOGIN_PASSWORD', '')


# Public legal pages (core.views.privacy / data_deletion). Meta requires a
# reachable privacy policy and data-deletion URL to publish the app; these
# two values are what those pages name as the responsible party, so set them
# to the real business before pointing Meta at the URLs.
LEGAL_ENTITY_NAME = os.environ.get('LEGAL_ENTITY_NAME', 'MVP CRM')
LEGAL_CONTACT_EMAIL = os.environ.get('LEGAL_CONTACT_EMAIL', 'sernasamuelperez@gmail.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# SQLite has no persistent filesystem to live on once deployed to Vercel's
# serverless functions, so any real deployment must set DATABASE_URL (e.g.
# via a Vercel Postgres / Neon integration). Local development keeps using
# SQLite with no configuration needed. `manage.py test` always uses SQLite too
# (see TESTING above), even when a developer's own .env points DATABASE_URL at
# a real database -- tests creating/dropping a scratch DB there is unwanted.

# dj_database_url carries the connection string's query parameters through
# into OPTIONS. That matters for Neon, whose URL ends in
# ?sslmode=require&channel_binding=require: parsing the URL by hand and
# copying out only NAME/USER/PASSWORD/HOST/PORT drops both, and libpq then
# falls back to sslmode=prefer, which silently accepts an unencrypted
# connection. conn_max_age keeps a connection alive across requests instead
# of reconnecting (and re-doing the TLS handshake) on every one.

if os.environ.get('DATABASE_URL') and not TESTING:
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Vercel's Django support runs `collectstatic` into STATIC_ROOT automatically
# during the build and serves the result from its CDN -- no extra config.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User uploads (WhatsApp media, template header media). Locally they live in
# MEDIA_ROOT, served by Django in DEBUG only -- see config/urls.py.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# In production there is no persistent filesystem (Vercel's functions are
# read-only + ephemeral), so uploads go to the project's Vercel Blob store
# instead: create it in the dashboard (Storage > Create Database > Blob) and
# connect it to the project, which injects BLOB_READ_WRITE_TOKEN into the
# environment -- its presence alone flips the default storage backend. Tests
# always keep the filesystem, even if a developer's .env carries the token.
if os.environ.get('BLOB_READ_WRITE_TOKEN') and not TESTING:
    STORAGES = {
        'default': {'BACKEND': 'core.storage.VercelBlobStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Messaging
# Which provider backs sending and webhooks: 'fake' | 'twilio' | 'meta' | 'baileys'.
# Swapping to a real provider is this one variable plus its credentials below
# (see .env.example). Values come from the environment so no credential ever
# lands in this file. `manage.py test` always forces 'fake' (see TESTING
# above), even when a developer's own .env is set to a real provider -- tests
# must not depend on a live sidecar/Twilio/Meta connection to pass.

MESSAGING_PROVIDER = 'fake' if TESTING else os.environ.get('MESSAGING_PROVIDER', 'fake')

# Fake provider: the shared secret dev webhooks must send in X-Fake-Signature.
MESSAGING_FAKE_SECRET = os.environ.get('MESSAGING_FAKE_SECRET', 'dev-secret')

# Template pricing (messaging/pricing.py). Sending a plantilla to a client
# outside the 24h window is billed per message, by category and country, so
# the CRM quotes the price before sending and records what each send cost.
#   MESSAGING_TEMPLATE_RATES -- your account's real price list, as JSON:
#     {"CO": {"marketing": "0.0125", "utility": "0.0022"}, "": {...}}
#     The "" row prices every country without one of its own. Unset means the
#     placeholder list in messaging/pricing.py, which is NOT Meta's real one.
#   MESSAGING_CURRENCY -- what those numbers are denominated in.
#   MESSAGING_MONTHLY_BUDGET -- optional ceiling per calendar month; a send
#     that would cross it is refused. 0 (the default) means no ceiling.
#
# How they are consumed. Environment variables are always strings, so all
# three are stored here as strings and parsed only where they are used, in
# messaging/pricing.py: rates() json.loads MESSAGING_TEMPLATE_RATES and
# overlays it country row by country row onto DEFAULT_RATES; currency()
# returns MESSAGING_CURRENCY, falling back to USD when it is empty; budget()
# turns MESSAGING_MONTHLY_BUDGET into a Decimal. Parsing there rather than
# here means a typo cannot stop Django from starting: a malformed price list
# is logged and the shipped defaults are used, a malformed budget is logged
# and treated as 0 (no ceiling).
#
# Those functions re-read django.conf.settings on every call and cache
# nothing, so the tests pin these with override_settings (see
# core.tests_plantilla_envio, messaging.tests_pricing and
# messaging.tests_envio_plantillas) and the change takes effect at once.
# Unlike MESSAGING_PROVIDER above, none of the three is forced to a value
# under TESTING.
#
# os.environ.get(NAME, default) returns the variable's value, or the default
# when it is unset; load_dotenv at the top of this file has already copied
# BASE_DIR/.env into os.environ, so a value in .env counts as set. The
# "Precio de las plantillas" block of .env.example documents all three.
MESSAGING_TEMPLATE_RATES = os.environ.get('MESSAGING_TEMPLATE_RATES', '')
MESSAGING_CURRENCY = os.environ.get('MESSAGING_CURRENCY', 'USD')
MESSAGING_MONTHLY_BUDGET = os.environ.get('MESSAGING_MONTHLY_BUDGET', '0')

# Twilio (unused until providers/twilio.py is implemented).
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '')

# Meta Cloud API (providers/meta.py). META_APP_SECRET signs incoming
# webhooks and META_VERIFY_TOKEN answers Meta's subscribe handshake --
# both fail closed when unset, so the webhook rejects traffic rather than
# trusting it. App Dashboard > App settings > Basic for the secret; the
# verify token is any string you also type into the webhook form.
META_ACCESS_TOKEN = os.environ.get('META_ACCESS_TOKEN', '')
META_PHONE_NUMBER_ID = os.environ.get('META_PHONE_NUMBER_ID', '')
META_APP_SECRET = os.environ.get('META_APP_SECRET', '')
META_VERIFY_TOKEN = os.environ.get('META_VERIFY_TOKEN', '')

# Baileys (unofficial WhatsApp Web/Desktop connection via a Node sidecar --
# see whatsapp-sidecar/. QR-code pairing, no Meta Developers app needed; good
# for demos, not for production -- see whatsapp-sidecar/README.md).
BAILEYS_SIDECAR_URL = os.environ.get('BAILEYS_SIDECAR_URL', 'http://localhost:4000')
BAILEYS_SIDECAR_SECRET = os.environ.get('BAILEYS_SIDECAR_SECRET', 'dev-sidecar-secret')
