"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# True under `manage.py test` (and pytest). core.middleware.LoginRequiredMiddleware
# reads this so the test client -- which never logs in -- isn't locked out.
# `manage.py test ...` (argv[1]) or a pytest run. Matching 'test' anywhere in
# argv, as this used to, also fired on any command that merely took 'test' as
# an argument -- and a process that believes it is testing quietly switches to
# SQLite, the fake provider and no login gate.
TESTING = (
    (len(sys.argv) > 1 and sys.argv[1] == 'test')
    or 'PYTEST_CURRENT_TEST' in os.environ
    or 'pytest' in sys.modules
)

# Load BASE_DIR/.env into os.environ before anything below reads it, so a
# plain `python manage.py ...` picks up local credentials with no `export`
# step. Real environment variables take precedence -- load_dotenv does not
# override what is already set -- so Vercel's project env vars win in
# production, where no .env file is deployed in the first place.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY in the environment for any real deployment (e.g. Vercel
# project env vars); this fallback is only for local development.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-r9ns&rk(gu0yvwjj&%#pepbj_oh_26h@pwex8#ch^x90+is@($',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Vercel sets VERCEL_URL to the deployment's hostname (no scheme) on every
# build, including preview deployments -- trust it automatically so the app
# works without listing every preview URL by hand. VERCEL_URL is per-deployment
# (e.g. mvp-crm-xxxxx.vercel.app) and does NOT cover the stable production
# alias, so VERCEL_PROJECT_PRODUCTION_URL is trusted too.
VERCEL_URL = os.environ.get('VERCEL_URL')
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)

VERCEL_PROJECT_PRODUCTION_URL = os.environ.get('VERCEL_PROJECT_PRODUCTION_URL')
if VERCEL_PROJECT_PRODUCTION_URL:
    ALLOWED_HOSTS.append(VERCEL_PROJECT_PRODUCTION_URL)

# Vercel also assigns this project two more stable aliases beyond
# VERCEL_PROJECT_PRODUCTION_URL (project-name-team-slug, and the git branch
# alias for main) -- hardcode them so they keep working without a dashboard
# env var edit. Only on Vercel (it sets VERCEL=1): locally these entries
# would make ALLOWED_HOSTS non-empty and disable Django's DEBUG-mode
# localhost fallback, locking the dev server out of its own machine.
if os.environ.get('VERCEL'):
    ALLOWED_HOSTS += [
        'mvp-crm-unaneaprogramadora.vercel.app',
        'mvp-crm-git-main-unaneaprogramadora.vercel.app',
    ]

# Absolute https origin for URLs that leave this app and are fetched by
# somebody else's servers -- specifically the image link handed to WhatsApp,
# which Meta rejects outright unless it is absolute ("Param image.link is not
# a valid URI"). Only needed when files are served by this app rather than a
# CDN; see core.storage.DatabaseStorage. A live request beats this (its Host
# is the origin the agent actually reached, and is validated against
# ALLOWED_HOSTS), so this is the fallback for code with no request in hand.
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', '').rstrip('/')
if not PUBLIC_BASE_URL and VERCEL_PROJECT_PRODUCTION_URL:
    PUBLIC_BASE_URL = f'https://{VERCEL_PROJECT_PRODUCTION_URL}'
if not PUBLIC_BASE_URL and ALLOWED_HOSTS:
    PUBLIC_BASE_URL = f'https://{ALLOWED_HOSTS[0]}'

CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

# Vercel terminates TLS in front of the app and forwards over HTTP; without
# this, request.is_secure() is always False behind the proxy, which breaks
# CSRF checks and any secure-cookie/redirect behavior.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS-only cookies and redirects, on exactly when the app is not in
# development. Without these the session and CSRF cookies go out over a
# deployed site without the Secure flag, so anything that can see the
# network can lift a session; `manage.py check --deploy` flags all three.
#
# Tied to DEBUG rather than to a variable of their own: a deployment already
# sets DEBUG=False (see .env.example), and a second switch is one more thing
# to forget. Local development stays on plain HTTP and is unaffected.
#
# SECURE_SSL_REDIRECT additionally sits out the test run. Django's test
# client speaks http://, so redirecting every insecure request would answer
# the whole suite with 301s instead of running it -- and TESTING already
# forces DEBUG off, which is what would otherwise switch this on.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG and not TESTING

# HSTS tells a browser to refuse plain HTTP for this domain for max-age
# seconds, and it CANNOT be taken back within that window -- a browser that
# has seen the header will not talk to the domain over HTTP again until it
# expires. That is why this one is opt-in by variable rather than following
# DEBUG like the three above: switch it on deliberately, on a domain that is
# fully on HTTPS and going to stay there, and start with a short max-age
# (say 3600) before raising it to a year (31536000).
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
# Both only mean anything while HSTS is on, and both widen its blast radius:
# INCLUDE_SUBDOMAINS covers every subdomain (including ones not on HTTPS
# yet), and PRELOAD asks browsers to ship the rule built in, which is far
# harder to undo than waiting out a max-age.
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
)
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'

# Who can log in, and who a conversation can be assigned to -- the same list
# either way (see core/agents.py for the format and the reasoning). Comma-
# separated `username:hash:Nombre` entries, e.g.
#   APP_AGENTS=Admin:pbkdf2_sha256$1500000$SALT$HASH=:Admin
# The middle field is a password hash, not a password -- generate one with
# `manage.py hashear_clave`. Blank means the gate can never be satisfied (see
# core.middleware), rather than an empty/empty login working.
APP_AGENTS = os.environ.get('APP_AGENTS', '')

# The pre-agents single pair, kept as a fallback so an environment that only
# sets these two still gets in -- core.agents treats it as a one-agent list.
APP_LOGIN_USERNAME = os.environ.get('APP_LOGIN_USERNAME', '')
APP_LOGIN_PASSWORD = os.environ.get('APP_LOGIN_PASSWORD', '')


# Public legal pages (core.views.privacy / data_deletion). Meta requires a
# reachable privacy policy and data-deletion URL to publish the app; these
# two values are what those pages name as the responsible party, so set them
# to the real business before pointing Meta at the URLs.
LEGAL_ENTITY_NAME = os.environ.get('LEGAL_ENTITY_NAME', 'MVP CRM')
LEGAL_CONTACT_EMAIL = os.environ.get('LEGAL_CONTACT_EMAIL', 'sernasamuelperez@gmail.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# SQLite has no persistent filesystem to live on once deployed to Vercel's
# serverless functions, so any real deployment must set DATABASE_URL (e.g.
# via a Vercel Postgres / Neon integration). Local development keeps using
# SQLite with no configuration needed. `manage.py test` always uses SQLite too
# (see TESTING above), even when a developer's own .env points DATABASE_URL at
# a real database -- tests creating/dropping a scratch DB there is unwanted.

# dj_database_url carries the connection string's query parameters through
# into OPTIONS. That matters for Neon, whose URL ends in
# ?sslmode=require&channel_binding=require: parsing the URL by hand and
# copying out only NAME/USER/PASSWORD/HOST/PORT drops both, and libpq then
# falls back to sslmode=prefer, which silently accepts an unencrypted
# connection. conn_max_age keeps a connection alive across requests instead
# of reconnecting (and re-doing the TLS handshake) on every one.

if os.environ.get('DATABASE_URL') and not TESTING:
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Vercel's Django support runs `collectstatic` into STATIC_ROOT automatically
# during the build and serves the result from its CDN -- no extra config.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User uploads (WhatsApp media, template header media). Locally they live in
# MEDIA_ROOT, served by Django in DEBUG only -- see config/urls.py.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# In production there is no persistent filesystem (Vercel's functions are
# read-only + ephemeral), so uploads go to the project's Vercel Blob store
# instead: create it in the dashboard (Storage > Create Database > Blob) and
# connect it to the project, which injects BLOB_READ_WRITE_TOKEN into the
# environment -- its presence alone flips the default storage backend. Tests
# always keep the filesystem, even if a developer's .env carries the token.
if os.environ.get('BLOB_READ_WRITE_TOKEN') and not TESTING:
    STORAGES = {
        'default': {'BACKEND': 'core.storage.VercelBlobStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
elif not TESTING and (
    os.environ.get('VERCEL')
    # VERCEL is a system environment variable, and a project can be configured
    # not to expose those -- in which case the check above is silently false
    # and uploads go back to failing on the read-only filesystem, with nothing
    # to see. Whether it is exposed on this project could not be confirmed
    # from outside (the alias that would have proved it sits behind Vercel
    # SSO), so don't rely on it alone: a real database plus DEBUG off is the
    # same "deployed, not a workstation" condition, reached independently.
    # Locally DEBUG is on and DATABASE_URL is commented out, so neither arm
    # fires and development keeps writing to MEDIA_ROOT.
    or (os.environ.get('DATABASE_URL') and not DEBUG)
):
    # On Vercel with no Blob store connected. The filesystem is read-only, so
    # FileSystemStorage would raise OSError(30) on the first byte written --
    # every image upload 500s, which is exactly what shipped. The database is
    # the only writable thing left, so uploads go there instead.
    #
    # This is the fallback, not the preference: the branch above wins whenever
    # a Blob store is connected, since a CDN serves files better than a row
    # store does. Connecting one later needs no code change -- only files
    # written while this branch was live stay in the database, and they keep
    # working, because their URLs are served from it either way.
    STORAGES = {
        'default': {'BACKEND': 'core.storage.DatabaseStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Messaging
# Which provider backs sending and webhooks: 'fake' | 'twilio' | 'meta'.
# Swapping to a real provider is this one variable plus its credentials below
# (see .env.example). Values come from the environment so no credential ever
# lands in this file. `manage.py test` always forces 'fake' (see TESTING
# above), even when a developer's own .env is set to a real provider -- tests
# must not depend on a live Twilio/Meta connection to pass. Outside
# tests the variable is required -- see the check below.

MESSAGING_PROVIDER = 'fake' if TESTING else os.environ.get('MESSAGING_PROVIDER', '')

# No silent default. 'fake' used to be the fallback, which meant a deploy
# missing the variable ran happily on simulated sends and simulated receipts
# -- ticks moving in the UI, nothing reaching a phone. Production is real
# customers writing in through the shared database; it must never run on the
# simulator by accident. Local development sets MESSAGING_PROVIDER=fake
# explicitly in .env (see .env.example).
if not MESSAGING_PROVIDER:
    raise ImproperlyConfigured(
        "MESSAGING_PROVIDER is not set. Choose 'twilio' or 'meta' for a real "
        "WhatsApp line, or 'fake' for local development only "
        "(see .env.example)."
    )

# The names messaging.providers.registry knows, repeated here as a literal on
# purpose: importing that module at settings time would pull in the app
# registry before Django is ready. A test asserts the two stay in step.
#
# An unknown value used to boot fine and fail later -- get_provider raised
# only when something tried to send, so the deployment looked healthy while
# every outbound message crashed and every webhook 404'd. It fails at startup
# now, which is the difference between a deploy that refuses and a CRM that
# quietly stops talking to customers.
MESSAGING_PROVIDERS = ('fake', 'twilio', 'meta')

if MESSAGING_PROVIDER not in MESSAGING_PROVIDERS:
    raise ImproperlyConfigured(
        f"MESSAGING_PROVIDER={MESSAGING_PROVIDER!r} is not a provider this app "
        f"has. Choose one of {', '.join(MESSAGING_PROVIDERS)}. A deployment "
        f"carrying the name of a provider that has since been removed lands "
        f"here: set the variable to one of those three."
    )

# Shared webhook secrets. Neither has a real default: a value committed to
# this file is a value an attacker already has, and both providers now reject
# every request while their secret is empty (fail closed, like Meta's). Under
# `manage.py test` they get a fixed value instead, so the signature-checking
# path is still exercised end to end rather than skipped.
#
# Fake provider: the secret dev webhooks send in X-Fake-Signature.
MESSAGING_FAKE_SECRET = (
    'testing-fake-secret' if TESTING else os.environ.get('MESSAGING_FAKE_SECRET', '')
)

# Template pricing (messaging/pricing.py). Sending a plantilla is billed per
# message by category and recipient market, so the CRM quotes the price before
# sending and records what each send cost.
#
# The rate card itself ships with the code (messaging/meta_rates.py holds
# Meta's published one), so none of these is required. They exist because a
# rate card is ultimately per *account*:
#
#   MESSAGING_TEMPLATE_RATES -- an overlay on Meta's card, as JSON keyed by
#     Meta's market names: {"Colombia": {"marketing": "0.0125"}, ...}. Merged
#     row by row, so what it does not name keeps Meta's number. Set it when
#     the account is billed at other rates (a BSP contract, a promotional
#     rate) or in another currency.
#   MESSAGING_CURRENCY -- what those numbers are denominated in. Meta's
#     shipped card is USD.
#   MESSAGING_MONTHLY_BUDGET -- optional ceiling per calendar month, in
#     MESSAGING_CURRENCY. Empty or unset means no limit;
#     services.send_template refuses a send that would cross it.
MESSAGING_TEMPLATE_RATES = os.environ.get('MESSAGING_TEMPLATE_RATES', '')
MESSAGING_CURRENCY = os.environ.get('MESSAGING_CURRENCY', 'USD')
MESSAGING_MONTHLY_BUDGET = os.environ.get('MESSAGING_MONTHLY_BUDGET', '')
#   MESSAGING_SERVICE_FREE_ALLOWANCE -- free service messages per phone
#     number per calendar month, before Meta starts charging for them (from
#     2026-10-01). Meta publishes 1000. Set it to 0 if this account has no
#     such allowance: it is the least well-corroborated part of that change,
#     so it is a variable rather than a constant.
MESSAGING_SERVICE_FREE_ALLOWANCE = os.environ.get(
    'MESSAGING_SERVICE_FREE_ALLOWANCE', '1000'
)

# Twilio (unused until providers/twilio.py is implemented).
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', '')

# Meta Cloud API (providers/meta.py). META_APP_SECRET signs incoming
# webhooks and META_VERIFY_TOKEN answers Meta's subscribe handshake --
# both fail closed when unset, so the webhook rejects traffic rather than
# trusting it. App Dashboard > App settings > Basic for the secret; the
# verify token is any string you also type into the webhook form.
META_ACCESS_TOKEN = os.environ.get('META_ACCESS_TOKEN', '')
META_PHONE_NUMBER_ID = os.environ.get('META_PHONE_NUMBER_ID', '')
META_APP_SECRET = os.environ.get('META_APP_SECRET', '')
META_VERIFY_TOKEN = os.environ.get('META_VERIFY_TOKEN', '')
# The template catalogue lives on the WhatsApp Business Account, not the phone
# number: submitting a plantilla for approval and reading verdicts back both
# go to /{META_WABA_ID}/message_templates. A media header's sample file is
# pushed through the Resumable Upload API, which is addressed by app id.
# Leave either empty and the CRM keeps plantillas locally, unsubmitted.
META_WABA_ID = os.environ.get('META_WABA_ID', '')
META_APP_ID = os.environ.get('META_APP_ID', '')
