# Generated by Django 6.1 on 2026-08-27 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_messagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram-dm', 'Instagram DM'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok-dm', 'Tiktok DM'), ('tiktok-coment', 'Tiktok comentarios')], default='whatsapp', max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('pending', 'Por resolver'), ('resolved', 'Resuelta')], default='open', max_length=10, verbose_name='estado')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='asignada a')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'conversación',
                'verbose_name_plural': 'conversaciones',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=8)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('failed', 'failed')], default='queued', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_message_at'], name='messaging_c_status_969cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='messaging_m_convers_91f1f5_idx'),
        ),
    ]
