# Generated by Django 6.1 on 2026-08-27 23:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('color', models.CharField(choices=[('green', 'Verde'), ('yellow', 'Amarillo'), ('purple', 'Morado'), ('blue', 'Azul'), ('red', 'Rojo'), ('orange', 'Naranja'), ('teal', 'Turquesa'), ('pink', 'Rosado'), ('indigo', 'Índigo'), ('gray', 'Gris')], default='gray', max_length=10, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='messaging.conversation')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_applied', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='messaging.tag')),
            ],
            options={
                'verbose_name': 'etiqueta de conversación',
                'verbose_name_plural': 'etiquetas de conversación',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='messaging.ConversationTag', to='messaging.tag', verbose_name='etiquetas'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='tag_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='conversationtag',
            constraint=models.UniqueConstraint(fields=('conversation', 'tag'), name='conversationtag_unique'),
        ),
    ]
