# Generated by Django 6.1 on 2026-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_tag_conversationtag_conversation_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
