# Generated by Django 6.1 on 2026-09-04 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messagetemplate_provider_sync'),
        ('messaging', '0003_message_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='billed_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='importe'),
        ),
        migrations.AddField(
            model_name='message',
            name='billed_category',
            field=models.CharField(blank=True, max_length=20, verbose_name='categoría facturada'),
        ),
        migrations.AddField(
            model_name='message',
            name='billed_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_billable',
            field=models.BooleanField(blank=True, null=True, verbose_name='facturable (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_category',
            field=models.CharField(blank=True, max_length=32, verbose_name='categoría facturada (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_model',
            field=models.CharField(blank=True, max_length=8, verbose_name='modelo de precio (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='tipo de precio (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.messagetemplate', verbose_name='plantilla'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('billed_amount__isnull', False)), fields=['timestamp'], name='message_billed_timestamp_idx'),
        ),
    ]
