# Generated by Django 6.1 on 2026-09-04 03:08
"""Add the template-billing columns to messaging.Message.

A migration is a Python description of one schema change. ``manage.py
makemigrations`` wrote this file by comparing ``messaging.models.Message``
with the state the earlier migrations describe; ``manage.py migrate`` turns
each operation below into SQL, runs it, and records the file's name in the
``django_migrations`` table so it runs exactly once per database. Run
``manage.py makemigrations --check`` yourself to confirm the model and this
file still agree; nothing in the project does it automatically.
Generated code: if the model changes again, run
``makemigrations`` for a new 0005 file instead of editing this one.

What it adds, all on the ``messaging_message`` table (the field comments in
messaging/models.py say why each exists):

* ``billed_amount``, ``billed_category``, ``billed_currency`` -- the price
  frozen onto a message by ``services.send_template``.
* ``template`` -- the plantilla the message was sent from.
* ``message_billed_timestamp_idx`` -- a partial index for the monthly spend
  query in ``messaging.pricing.spent_between``.

Existing rows keep meaning what they meant: the two nullable columns get
NULL (an unbilled, non-template message) and the two text columns get ''
(Django adds a ``blank=True`` CharField using the empty string as its
effective default), so no old message suddenly looks billed.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Migrations that must already be applied before this one runs. Django
    # pins the *newest* migration of each app referenced at generation time,
    # not the one that created the target model (core.MessageTemplate dates
    # from core 0004), which is why 0008_calendarevent appears here.
    dependencies = [
        # For the ForeignKey to core.MessageTemplate: that table must exist.
        ('core', '0008_calendarevent'),
        # The previous migration of this app: every new migration depends on
        # the app's latest one, so they apply in order.
        ('messaging', '0003_message_media_type'),
        # Not touched by any operation below. The AddIndex makes Django list
        # every model the indexed table relates to, and Message.sent_by
        # points at the user model. ``swappable_dependency`` resolves
        # AUTH_USER_MODEL to whichever app provides it (django.contrib.auth
        # here) at migrate time.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Applied in order, inside one transaction on databases with
    # transactional DDL (SQLite and PostgreSQL both have it), so a failure
    # halfway leaves the table untouched.
    operations = [
        # Each AddField becomes ``ALTER TABLE messaging_message ADD
        # COLUMN`` on PostgreSQL; on SQLite (this project's default) Django
        # rebuilds the whole table for the two NOT NULL text columns and
        # uses ADD COLUMN only for the nullable ones.
        # The keyword arguments repeat the field definition from models.py
        # because migrations must be self-contained: Django rebuilds the
        # model's historical state from these files alone, without importing
        # the current models. That is why ``verbose_name`` and
        # ``related_name`` are recorded too, although they produce no SQL --
        # leaving them out would make ``makemigrations`` think the model
        # still differs from the migrations.
        migrations.AddField(
            model_name='message',
            name='billed_amount',
            # A 12-digit, 6-decimal numeric column, nullable: NULL means
            # "not billed".
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='importe'),
        ),
        migrations.AddField(
            model_name='message',
            name='billed_category',
            # 20-character NOT NULL text column; existing rows get ''.
            field=models.CharField(blank=True, max_length=20, verbose_name='categoría facturada'),
        ),
        migrations.AddField(
            model_name='message',
            name='billed_currency',
            # 3-character NOT NULL text column (an ISO 4217 code such as
            # USD); existing rows get ''.
            field=models.CharField(blank=True, max_length=3, verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            # Creates the nullable ``template_id`` column plus its
            # foreign-key constraint and index. ``to`` is the lowercase
            # "app.model" label. SET_NULL is carried out by Django when a
            # plantilla is deleted through the ORM, not by the database.
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.messagetemplate', verbose_name='plantilla'),
        ),
        # ``CREATE INDEX message_billed_timestamp_idx ON messaging_message
        # (timestamp) WHERE billed_amount IS NOT NULL``. The Q object is the
        # WHERE clause, written as a ('lookup', value) tuple -- the form a Q
        # takes when serialised into a migration.
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('billed_amount__isnull', False)), fields=['timestamp'], name='message_billed_timestamp_idx'),
        ),
    ]
