# Generated by Django 6.1 on 2026-09-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta_billable',
            field=models.BooleanField(blank=True, null=True, verbose_name='facturable (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_category',
            field=models.CharField(blank=True, max_length=32, verbose_name='categoría facturada (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_model',
            field=models.CharField(blank=True, max_length=8, verbose_name='modelo de precio (Meta)'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_pricing_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='tipo de precio (Meta)'),
        ),
    ]
