# Generated by Django 6.1 on 2026-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_meta_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='billed_as_service',
            field=models.BooleanField(default=False, verbose_name='cobrado como servicio'),
        ),
    ]
