"""Meta's published WhatsApp per-message rate card, as data.

Not hand-typed: generated from the CSV files Meta links from
https://developers.facebook.com/docs/whatsapp/pricing#rate-cards -- the same
figures WhatsApp Manager bills against. Those download links are signed and
expire, so there is no stable URL to fetch at run time; the card is
transcribed here and re-checked when Meta publishes a new one (Meta may change
rates on Jan 1 / Apr 1 / Jul 1 / Oct 1, with at least a month's notice).

Two cards live here at once because Meta publishes the next one ahead of time.
:func:`messaging.pricing.card_for` picks by date, so the quote a CRM shows
switches over on its own the day a card takes effect.

Every amount is a *string* -- ``Decimal`` cannot be written as a literal and a
float would already have lost the value ({"Colombia": "0.0008"} is exactly the
kind of figure that drifts). :mod:`messaging.pricing` converts them.

Prices are per *delivered* template message, in USD, and Meta charges on
delivery rather than on send: a quote made before sending is an estimate until
the delivery receipt arrives.

Categories a row may carry: ``marketing``, ``utility``, ``authentication``,
``authentication_international`` and ``service``. A category missing from a row
is "n/a" on Meta's card for that market -- there is no rate, not a rate of
zero. (On the July 2026 card every market's ``service`` is n/a: service
messages are free until 2026-09-30.)
"""

from __future__ import annotations

from datetime import date

#: Where these numbers come from, for the next person who has to refresh them.
SOURCE_DOC = "https://developers.facebook.com/docs/whatsapp/pricing#rate-cards"
COUNTRY_CODES_DOC = (
    "https://developers.facebook.com/docs/whatsapp/pricing#country-calling-codes"
)

#: Meta's cards, oldest first. Each row maps a *market* (Meta's own name for a
#: country or regional bucket) to its per-category price.
RATE_CARDS = [
    {
        "effective": date.fromisoformat("2026-07-01"),
        "currency": "USD",
        "title": "Cost per message in USD on the WhatsApp Business Platform, effective July 1, 2026",
        "rows": {
        "Argentina": {"marketing": "0.0618", "utility": "0.0260", "authentication": "0.0260",},
        "Brazil": {"marketing": "0.0625", "utility": "0.0068", "authentication": "0.0068",},
        "Chile": {"marketing": "0.0889", "utility": "0.0200", "authentication": "0.0200",},
        "Colombia": {"marketing": "0.0125", "utility": "0.0008", "authentication": "0.0008",},
        "Egypt": {"marketing": "0.0644", "utility": "0.0036", "authentication": "0.0036", "authentication_international": "0.0650",},
        "France": {"marketing": "0.0859", "utility": "0.0300", "authentication": "0.0300",},
        "Germany": {"marketing": "0.1365", "utility": "0.0550", "authentication": "0.0550",},
        "Hong Kong": {"marketing": "0.0732", "utility": "0.0260", "authentication": "0.0260",},
        "Hungary": {"marketing": "0.0860", "utility": "0.0350", "authentication": "0.0350",},
        "India": {"marketing": "0.0118", "utility": "0.0014", "authentication": "0.0014", "authentication_international": "0.0304",},
        "Indonesia": {"marketing": "0.0411", "utility": "0.0250", "authentication": "0.0250", "authentication_international": "0.1360",},
        "Israel": {"marketing": "0.0353", "utility": "0.0053", "authentication": "0.0053",},
        "Italy": {"marketing": "0.0795", "utility": "0.0300", "authentication": "0.0300",},
        "Malaysia": {"marketing": "0.0860", "utility": "0.0140", "authentication": "0.0140", "authentication_international": "0.0418",},
        "Mexico": {"marketing": "0.0305", "utility": "0.0085", "authentication": "0.0085",},
        "Netherlands": {"marketing": "0.1597", "utility": "0.0500", "authentication": "0.0500",},
        "Nigeria": {"marketing": "0.0516", "utility": "0.0067", "authentication": "0.0067", "authentication_international": "0.0750",},
        "North America": {"marketing": "0.0250", "utility": "0.0034", "authentication": "0.0034",},
        "Other": {"marketing": "0.0604", "utility": "0.0077", "authentication": "0.0077",},
        "Pakistan": {"marketing": "0.0473", "utility": "0.0100", "authentication": "0.0100", "authentication_international": "0.0750",},
        "Peru": {"marketing": "0.0703", "utility": "0.0200", "authentication": "0.0200",},
        "Poland": {"marketing": "0.0366", "utility": "0.0122", "authentication": "0.0122",},
        "Qatar": {"marketing": "0.0341", "utility": "0.0120", "authentication": "0.0120",},
        "Rest of Africa": {"marketing": "0.0225", "utility": "0.0040", "authentication": "0.0040",},
        "Rest of Asia Pacific": {"marketing": "0.0732", "utility": "0.0113", "authentication": "0.0113",},
        "Rest of Central & Eastern Europe": {"marketing": "0.0860", "utility": "0.0212", "authentication": "0.0212",},
        "Rest of Latin America": {"marketing": "0.0740", "utility": "0.0113", "authentication": "0.0113",},
        "Rest of Middle East": {"marketing": "0.0341", "utility": "0.0091", "authentication": "0.0091",},
        "Rest of Western Europe": {"marketing": "0.0592", "utility": "0.0171", "authentication": "0.0171",},
        "Romania": {"marketing": "0.0860", "utility": "0.0290", "authentication": "0.0290",},
        "Russia": {"marketing": "0.0802", "utility": "0.0400", "authentication": "0.0400",},
        "Saudi Arabia": {"marketing": "0.0501", "utility": "0.0107", "authentication": "0.0107", "authentication_international": "0.0598",},
        "Singapore": {"marketing": "0.0732", "utility": "0.0160", "authentication": "0.0160",},
        "South Africa": {"marketing": "0.0379", "utility": "0.0076", "authentication": "0.0076", "authentication_international": "0.0200",},
        "Spain": {"marketing": "0.0707", "utility": "0.0200", "authentication": "0.0200",},
        "Turkey": {"marketing": "0.0109", "utility": "0.0009", "authentication": "0.0009",},
        "United Arab Emirates": {"marketing": "0.0499", "utility": "0.0157", "authentication": "0.0157", "authentication_international": "0.0510",},
        "United Kingdom": {"marketing": "0.0635", "utility": "0.0220", "authentication": "0.0220",},
        },
    },
    {
        "effective": date.fromisoformat("2026-10-01"),
        "currency": "USD",
        "title": "Cost per message in USD on the WhatsApp Business Platform, effective October 1, 2026",
        "rows": {
        "Argentina": {"marketing": "0.0618", "utility": "0.026", "authentication": "0.026", "service": "0.026",},
        "Bangladesh": {"marketing": "0.0732", "utility": "0.0037", "authentication": "0.0037", "authentication_international": "0.096", "service": "0.0037",},
        "Brazil": {"marketing": "0.0625", "utility": "0.0068", "authentication": "0.0068", "service": "0.0068",},
        "Chile": {"marketing": "0.0889", "utility": "0.02", "authentication": "0.02", "service": "0.02",},
        "Colombia": {"marketing": "0.0125", "utility": "0.0008", "authentication": "0.0008", "service": "0.0008",},
        "Egypt": {"marketing": "0.0644", "utility": "0.0036", "authentication": "0.0036", "authentication_international": "0.065", "service": "0.0036",},
        "France": {"marketing": "0.0859", "utility": "0.03", "authentication": "0.03", "service": "0.03",},
        "Germany": {"marketing": "0.1365", "utility": "0.055", "authentication": "0.055", "service": "0.055",},
        "Hong Kong": {"marketing": "0.0732", "utility": "0.026", "authentication": "0.026", "service": "0.026",},
        "Hungary": {"marketing": "0.086", "utility": "0.035", "authentication": "0.035", "service": "0.035",},
        "India": {"marketing": "0.0118", "utility": "0.0014", "authentication": "0.0014", "authentication_international": "0.0304", "service": "0.0014",},
        "Indonesia": {"marketing": "0.0411", "utility": "0.025", "authentication": "0.025", "authentication_international": "0.136", "service": "0.025",},
        "Iraq": {"marketing": "0.0341", "utility": "0.0079", "authentication": "0.0079", "authentication_international": "0.128", "service": "0.0079",},
        "Israel": {"marketing": "0.0353", "utility": "0.0053", "authentication": "0.0053", "service": "0.0053",},
        "Italy": {"marketing": "0.0795", "utility": "0.03", "authentication": "0.03", "service": "0.03",},
        "Kazakhstan": {"marketing": "0.0604", "utility": "0.018", "authentication": "0.018", "authentication_international": "0.16", "service": "0.018",},
        "Kuwait": {"marketing": "0.0792", "utility": "0.044", "authentication": "0.044", "authentication_international": "0.12", "service": "0.044",},
        "Malaysia": {"marketing": "0.086", "utility": "0.014", "authentication": "0.014", "authentication_international": "0.0418", "service": "0.014",},
        "Mexico": {"marketing": "0.0397", "utility": "0.0085", "authentication": "0.0085", "service": "0.0085",},
        "Morocco": {"marketing": "0.0414", "utility": "0.023", "authentication": "0.023", "authentication_international": "0.0811", "service": "0.023",},
        "Nepal": {"marketing": "0.0732", "utility": "0.0034", "authentication": "0.0034", "authentication_international": "0.112", "service": "0.0034",},
        "Netherlands": {"marketing": "0.1597", "utility": "0.05", "authentication": "0.05", "service": "0.05",},
        "Nigeria": {"marketing": "0.0516", "utility": "0.0067", "authentication": "0.0067", "authentication_international": "0.075", "service": "0.0067",},
        "North America": {"marketing": "0.025", "utility": "0.0034", "authentication": "0.0034", "service": "0.0034",},
        "Oman": {"marketing": "0.0341", "utility": "0.0247", "authentication": "0.0247", "authentication_international": "0.06", "service": "0.0247",},
        "Other": {"marketing": "0.0604", "utility": "0.0077", "authentication": "0.0077", "service": "0.0077",},
        "Pakistan": {"marketing": "0.0473", "utility": "0.015", "authentication": "0.015", "authentication_international": "0.075", "service": "0.015",},
        "Peru": {"marketing": "0.0703", "utility": "0.03", "authentication": "0.03", "service": "0.03",},
        "Poland": {"marketing": "0.0366", "utility": "0.0122", "authentication": "0.0122", "service": "0.0122",},
        "Qatar": {"marketing": "0.0341", "utility": "0.012", "authentication": "0.012", "service": "0.012",},
        "Rest of Africa": {"marketing": "0.0225", "utility": "0.004", "authentication": "0.004", "service": "0.004",},
        "Rest of Asia Pacific": {"marketing": "0.0842", "utility": "0.0113", "authentication": "0.0113", "service": "0.0113",},
        "Rest of Central & Eastern Europe": {"marketing": "0.086", "utility": "0.0212", "authentication": "0.0212", "service": "0.0212",},
        "Rest of Latin America": {"marketing": "0.074", "utility": "0.0113", "authentication": "0.0113", "service": "0.0113",},
        "Rest of Middle East": {"marketing": "0.0392", "utility": "0.0091", "authentication": "0.0091", "service": "0.0091",},
        "Rest of Western Europe": {"marketing": "0.0592", "utility": "0.0171", "authentication": "0.0171", "service": "0.0171",},
        "Romania": {"marketing": "0.086", "utility": "0.029", "authentication": "0.029", "service": "0.029",},
        "Russia": {"marketing": "0.0802", "utility": "0.04", "authentication": "0.04", "service": "0.04",},
        "Saudi Arabia": {"marketing": "0.0576", "utility": "0.0107", "authentication": "0.0107", "authentication_international": "0.0598", "service": "0.0107",},
        "Singapore": {"marketing": "0.0732", "utility": "0.016", "authentication": "0.016", "service": "0.016",},
        "South Africa": {"marketing": "0.0379", "utility": "0.0095", "authentication": "0.0095", "authentication_international": "0.02", "service": "0.0095",},
        "Spain": {"marketing": "0.0707", "utility": "0.02", "authentication": "0.02", "service": "0.02",},
        "Sri Lanka": {"marketing": "0.0732", "utility": "0.002", "authentication": "0.002", "authentication_international": "0.144", "service": "0.002",},
        "Turkey": {"marketing": "0.0109", "utility": "0.0009", "authentication": "0.0009", "service": "0.0009",},
        "Ukraine": {"marketing": "0.086", "utility": "0.0298", "authentication": "0.0298", "authentication_international": "0.0746", "service": "0.0298",},
        "United Arab Emirates": {"marketing": "0.0576", "utility": "0.0157", "authentication": "0.0157", "authentication_international": "0.051", "service": "0.0157",},
        "United Kingdom": {"marketing": "0.0635", "utility": "0.022", "authentication": "0.022", "service": "0.022",},
        },
    },
]

#: ISO 3166-1 alpha-2 -> the market whose rates that country is billed at.
#: Countries with no rate of their own sit in a regional bucket ("Rest of
#: Latin America" covers Ecuador, Panama, Uruguay and a dozen more).
MARKET_BY_ISO = {
    "AE": "United Arab Emirates",
    "AF": "Rest of Asia Pacific",
    "AL": "Rest of Central & Eastern Europe",
    "AM": "Rest of Central & Eastern Europe",
    "AO": "Rest of Africa",
    "AR": "Argentina",
    "AT": "Rest of Western Europe",
    "AU": "Rest of Asia Pacific",
    "AZ": "Rest of Central & Eastern Europe",
    "BD": "Rest of Asia Pacific",
    "BE": "Rest of Western Europe",
    "BF": "Rest of Africa",
    "BG": "Rest of Central & Eastern Europe",
    "BH": "Rest of Middle East",
    "BI": "Rest of Africa",
    "BJ": "Rest of Africa",
    "BO": "Rest of Latin America",
    "BR": "Brazil",
    "BW": "Rest of Africa",
    "BY": "Rest of Central & Eastern Europe",
    "CA": "North America",
    "CG": "Rest of Africa",
    "CH": "Rest of Western Europe",
    "CI": "Rest of Africa",
    "CL": "Chile",
    "CM": "Rest of Africa",
    "CN": "Rest of Asia Pacific",
    "CO": "Colombia",
    "CR": "Rest of Latin America",
    "CZ": "Rest of Central & Eastern Europe",
    "DE": "Germany",
    "DK": "Rest of Western Europe",
    "DO": "Rest of Latin America",
    "DZ": "Rest of Africa",
    "EC": "Rest of Latin America",
    "EG": "Egypt",
    "ER": "Rest of Africa",
    "ES": "Spain",
    "ET": "Rest of Africa",
    "FI": "Rest of Western Europe",
    "FR": "France",
    "GA": "Rest of Africa",
    "GB": "United Kingdom",
    "GE": "Rest of Central & Eastern Europe",
    "GH": "Rest of Africa",
    "GM": "Rest of Africa",
    "GR": "Rest of Central & Eastern Europe",
    "GT": "Rest of Latin America",
    "GW": "Rest of Africa",
    "HK": "Hong Kong",
    "HN": "Rest of Latin America",
    "HR": "Rest of Central & Eastern Europe",
    "HT": "Rest of Latin America",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Rest of Western Europe",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Rest of Middle East",
    "IT": "Italy",
    "JM": "Rest of Latin America",
    "JO": "Rest of Middle East",
    "JP": "Rest of Asia Pacific",
    "KE": "Rest of Africa",
    "KH": "Rest of Asia Pacific",
    "KW": "Rest of Middle East",
    "LA": "Rest of Asia Pacific",
    "LB": "Rest of Middle East",
    "LK": "Rest of Asia Pacific",
    "LR": "Rest of Africa",
    "LS": "Rest of Africa",
    "LT": "Rest of Central & Eastern Europe",
    "LV": "Rest of Central & Eastern Europe",
    "LY": "Rest of Africa",
    "MA": "Rest of Africa",
    "MD": "Rest of Central & Eastern Europe",
    "MG": "Rest of Africa",
    "MK": "Rest of Central & Eastern Europe",
    "ML": "Rest of Africa",
    "MN": "Rest of Asia Pacific",
    "MR": "Rest of Africa",
    "MW": "Rest of Africa",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Rest of Africa",
    "NA": "Rest of Africa",
    "NE": "Rest of Africa",
    "NG": "Nigeria",
    "NI": "Rest of Latin America",
    "NL": "Netherlands",
    "NO": "Rest of Western Europe",
    "NP": "Rest of Asia Pacific",
    "NZ": "Rest of Asia Pacific",
    "OM": "Rest of Middle East",
    "PA": "Rest of Latin America",
    "PE": "Peru",
    "PG": "Rest of Asia Pacific",
    "PH": "Rest of Asia Pacific",
    "PK": "Pakistan",
    "PL": "Poland",
    "PR": "Rest of Latin America",
    "PT": "Rest of Western Europe",
    "PY": "Rest of Latin America",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Rest of Central & Eastern Europe",
    "RU": "Russia",
    "RW": "Rest of Africa",
    "SA": "Saudi Arabia",
    "SD": "Rest of Africa",
    "SE": "Rest of Western Europe",
    "SG": "Singapore",
    "SI": "Rest of Central & Eastern Europe",
    "SK": "Rest of Central & Eastern Europe",
    "SL": "Rest of Africa",
    "SN": "Rest of Africa",
    "SO": "Rest of Africa",
    "SS": "Rest of Africa",
    "SV": "Rest of Latin America",
    "SZ": "Rest of Africa",
    "TD": "Rest of Africa",
    "TG": "Rest of Africa",
    "TH": "Rest of Asia Pacific",
    "TJ": "Rest of Asia Pacific",
    "TM": "Rest of Asia Pacific",
    "TN": "Rest of Africa",
    "TR": "Turkey",
    "TW": "Rest of Asia Pacific",
    "TZ": "Rest of Africa",
    "UA": "Rest of Central & Eastern Europe",
    "UG": "Rest of Africa",
    "US": "North America",
    "UY": "Rest of Latin America",
    "UZ": "Rest of Asia Pacific",
    "VE": "Rest of Latin America",
    "VN": "Rest of Asia Pacific",
    "YE": "Rest of Middle East",
    "ZA": "South Africa",
    "ZM": "Rest of Africa",
    "ZW": "Rest of Africa",
}

#: E.164 calling code -> market, longest match first (see
#: ``pricing.market_for_phone``): "57" is Colombia, "1" is North America.
MARKET_BY_CALLING_CODE = {
    "1": "North America",
    "20": "Egypt",
    "211": "Rest of Africa",
    "212": "Rest of Africa",
    "213": "Rest of Africa",
    "216": "Rest of Africa",
    "218": "Rest of Africa",
    "220": "Rest of Africa",
    "221": "Rest of Africa",
    "222": "Rest of Africa",
    "223": "Rest of Africa",
    "225": "Rest of Africa",
    "226": "Rest of Africa",
    "227": "Rest of Africa",
    "228": "Rest of Africa",
    "229": "Rest of Africa",
    "231": "Rest of Africa",
    "232": "Rest of Africa",
    "233": "Rest of Africa",
    "234": "Nigeria",
    "235": "Rest of Africa",
    "237": "Rest of Africa",
    "241": "Rest of Africa",
    "242": "Rest of Africa",
    "244": "Rest of Africa",
    "245": "Rest of Africa",
    "249": "Rest of Africa",
    "250": "Rest of Africa",
    "251": "Rest of Africa",
    "252": "Rest of Africa",
    "254": "Rest of Africa",
    "255": "Rest of Africa",
    "256": "Rest of Africa",
    "257": "Rest of Africa",
    "258": "Rest of Africa",
    "260": "Rest of Africa",
    "261": "Rest of Africa",
    "263": "Rest of Africa",
    "264": "Rest of Africa",
    "265": "Rest of Africa",
    "266": "Rest of Africa",
    "267": "Rest of Africa",
    "268": "Rest of Africa",
    "27": "South Africa",
    "291": "Rest of Africa",
    "30": "Rest of Central & Eastern Europe",
    "31": "Netherlands",
    "32": "Rest of Western Europe",
    "33": "France",
    "34": "Spain",
    "351": "Rest of Western Europe",
    "353": "Rest of Western Europe",
    "355": "Rest of Central & Eastern Europe",
    "358": "Rest of Western Europe",
    "359": "Rest of Central & Eastern Europe",
    "36": "Hungary",
    "370": "Rest of Central & Eastern Europe",
    "371": "Rest of Central & Eastern Europe",
    "373": "Rest of Central & Eastern Europe",
    "374": "Rest of Central & Eastern Europe",
    "375": "Rest of Central & Eastern Europe",
    "380": "Rest of Central & Eastern Europe",
    "381": "Rest of Central & Eastern Europe",
    "385": "Rest of Central & Eastern Europe",
    "386": "Rest of Central & Eastern Europe",
    "389": "Rest of Central & Eastern Europe",
    "39": "Italy",
    "40": "Romania",
    "41": "Rest of Western Europe",
    "420": "Rest of Central & Eastern Europe",
    "421": "Rest of Central & Eastern Europe",
    "43": "Rest of Western Europe",
    "44": "United Kingdom",
    "45": "Rest of Western Europe",
    "46": "Rest of Western Europe",
    "47": "Rest of Western Europe",
    "48": "Poland",
    "49": "Germany",
    "502": "Rest of Latin America",
    "503": "Rest of Latin America",
    "504": "Rest of Latin America",
    "505": "Rest of Latin America",
    "506": "Rest of Latin America",
    "507": "Rest of Latin America",
    "509": "Rest of Latin America",
    "51": "Peru",
    "52": "Mexico",
    "54": "Argentina",
    "55": "Brazil",
    "56": "Chile",
    "57": "Colombia",
    "58": "Rest of Latin America",
    "591": "Rest of Latin America",
    "593": "Rest of Latin America",
    "595": "Rest of Latin America",
    "598": "Rest of Latin America",
    "60": "Malaysia",
    "61": "Rest of Asia Pacific",
    "62": "Indonesia",
    "63": "Rest of Asia Pacific",
    "64": "Rest of Asia Pacific",
    "65": "Singapore",
    "66": "Rest of Asia Pacific",
    "675": "Rest of Asia Pacific",
    "7": "Russia",
    "81": "Rest of Asia Pacific",
    "84": "Rest of Asia Pacific",
    "852": "Hong Kong",
    "855": "Rest of Asia Pacific",
    "856": "Rest of Asia Pacific",
    "86": "Rest of Asia Pacific",
    "880": "Rest of Asia Pacific",
    "886": "Rest of Asia Pacific",
    "90": "Turkey",
    "91": "India",
    "92": "Pakistan",
    "93": "Rest of Asia Pacific",
    "94": "Rest of Asia Pacific",
    "961": "Rest of Middle East",
    "962": "Rest of Middle East",
    "964": "Rest of Middle East",
    "965": "Rest of Middle East",
    "966": "Saudi Arabia",
    "967": "Rest of Middle East",
    "968": "Rest of Middle East",
    "971": "United Arab Emirates",
    "972": "Israel",
    "973": "Rest of Middle East",
    "974": "Qatar",
    "976": "Rest of Asia Pacific",
    "977": "Rest of Asia Pacific",
    "992": "Rest of Asia Pacific",
    "993": "Rest of Asia Pacific",
    "994": "Rest of Central & Eastern Europe",
    "995": "Rest of Central & Eastern Europe",
    "998": "Rest of Asia Pacific",
}

#: The +1 trap. Dominican Republic, Jamaica and Puerto Rico share calling code
#: 1 with the US and Canada but bill at "Rest of Latin America" -- 0.0740
#: against North America's 0.0250 for marketing, a ~3x error in the customer's
#: favour or ours depending on which way you get it wrong. A +1 number must be
#: resolved by its three-digit NANP area code before falling back to North
#: America.
MARKET_BY_NANP_AREA = {
    "658": "Rest of Latin America",
    "787": "Rest of Latin America",
    "809": "Rest of Latin America",
    "829": "Rest of Latin America",
    "849": "Rest of Latin America",
    "876": "Rest of Latin America",
    "939": "Rest of Latin America",
}

#: Markets that charge the premium "authentication-international" rate, and
#: the date each list applies from. It only bites a business sending more than
#: 750K messages outside customer service windows in a rolling 30 days, and
#: never applies to the business's own primary location.
AUTHENTICATION_INTERNATIONAL_MARKETS = {
    date.fromisoformat("2026-07-01"): ["Egypt", "India", "Indonesia", "Malaysia", "Nigeria", "Pakistan", "Saudi Arabia", "South Africa", "United Arab Emirates"],
    date.fromisoformat("2026-10-01"): ["Bangladesh", "Egypt", "India", "Indonesia", "Iraq", "Kazakhstan", "Kuwait", "Malaysia", "Morocco", "Nepal", "Nigeria", "Oman", "Pakistan", "Saudi Arabia", "South Africa", "Sri Lanka", "Ukraine", "United Arab Emirates"],
}

#: Marketing has no volume tiers -- the list rate always applies. Utility and
#: authentication earn 5%-25% discounts (6%-30% in India) once a business
#: portfolio's monthly volume for that market+category crosses a threshold.
#: Tier standing is an account-wide fact this CRM cannot see, so quotes use
#: tier 1 (the undiscounted list rate) and can only over-estimate, never
#: under-estimate, what Meta will charge.
VOLUME_TIERS_APPLY_TO = ("utility", "authentication")
